### ISSUE TITLE
Revived players spawn at boom/fake bodies location

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-wep_defi#16]
If you try to revive a real body then he will respawn at the location of the boom body/fake body and not at the location of the real body which you tried to revive.
The revived player has the boom body radar tag attached to him and nothing happens with the real body.
Using the Steam Workshop version and newest TTT2 Base version from the Steam Workshop.

See video: https://streamable.com/w9v5tw

**Comment by TimGoll** [comment]
Closing this, as this is an issue in TTT2
