### ISSUE TITLE
Revival bug for fake bodies/boom bodies

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-wep_defi#2]
I have already written this bug here: https://steamcommunity.com/sharedfiles/filedetails/?id=1473581448 in the comment section of LeBrommer's "[TTT2/TTT] Death Faker (fixed and improved)" but i will write it here too because it seems that the Defi is the issue. 

If someone has placed a fake body or boom body and tries to revive it with the Defi then the revival will work: 
If the fake body is from Bot1 and not you and someone tries to revive the fake body then Bot1 will be revived. You can only revive fake bodies/boom bodies if the real person is dead. Then the revival will work. 

If you use the necro defi then it doesn't matter if you try to revive your own fake body/boom body or someone else and it doesn't matter if the person is still alive or not. The person will be teleported to the postion of the fake body/boom body and will be in Team Zombie. In some cases the person will still have all weapons equiped.

How to reproduce: 
1. Create Game and spawn some bots
2. Place fake body/boom body 
3. Make yourself Necromancer
4. Try to revive the fake body/boom body
5. Result

or

1. Create Game and spawn some bots
2. Place a fake body of someone else (bot1)
3. Kill bot1
4. Try to revive him with the normal defi from the traitor/detective shop
5. Result

Tested everything with the Workshop Versions. 
Here a video how it looks like: https://streamable.com/2655jt

**Comment by TimGoll** [comment]
Thanks for the detailed report. I'm quite busy at the moment with examps. But I'll look into it as soon as I have the time for it.

**Comment by mexikoedi** [comment]
Closing this Issue because the above mentioned PR fixed this Issue.
